export interface RepoAssetContext {
	owner: string;
	repo: string;
	ref: string;
	filePath: string;
}

function encodeRef(ref: string): string {
	return ref
		.split("/")
		.map((segment) => encodeURIComponent(segment))
		.join("/");
}

function encodePath(path: string): string {
	return path
		.split("/")
		.map((segment) => encodeURIComponent(segment))
		.join("/");
}

function decodePath(path: string): string | null {
	try {
		return decodeURIComponent(path);
	} catch {
		return null;
	}
}

/**
 * Resolves an image source from rendered Markdown to a repository-relative path.
 *
 * GitHub's Markdown renderer may leave relative URLs relative to the Markdown
 * file, or turn them into GitHub/raw URLs. We normalize both forms so the
 * server can later fetch the private asset through the GitHub App.
 */
export function resolveRepoImagePath(
	rawSrc: string,
	context: RepoAssetContext,
): string | null {
	if (
		!rawSrc ||
		rawSrc.startsWith("#") ||
		rawSrc.startsWith("data:") ||
		rawSrc.startsWith("blob:")
	) {
		return null;
	}

	const githubBase = `https://github.com/${encodeURIComponent(
		context.owner,
	)}/${encodeURIComponent(context.repo)}/blob/${encodeRef(
		context.ref,
	)}/${encodePath(context.filePath)}`;

	let url: URL;

	try {
		url = new URL(rawSrc, githubBase);
	} catch {
		return null;
	}

	const owner = context.owner.toLowerCase();
	const repo = context.repo.toLowerCase();

	if (url.hostname === "raw.githubusercontent.com") {
		const prefix = `/${encodeURIComponent(context.owner)}/${encodeURIComponent(
			context.repo,
		)}/${encodeRef(context.ref)}/`;

		if (!url.pathname.startsWith(prefix)) {
			return null;
		}

		const path = decodePath(url.pathname.slice(prefix.length));
		return path || null;
	}

	if (url.hostname !== "github.com") {
		return null;
	}

	const pathname = url.pathname;

	const repoPrefix = `/${encodeURIComponent(context.owner)}/${encodeURIComponent(context.repo)}/`;

	if (!pathname.toLowerCase().startsWith(repoPrefix.toLowerCase())) {
		return null;
	}

	const afterRepo = pathname.slice(repoPrefix.length);

	const prefixes = [
		`blob/${encodeRef(context.ref)}/`,
		`raw/${encodeRef(context.ref)}/`,
		`raw/refs/heads/${encodeRef(context.ref)}/`,
	];

	for (const prefix of prefixes) {
		if (afterRepo.startsWith(prefix)) {
			const path = decodePath(afterRepo.slice(prefix.length));
			return path || null;
		}
	}

	// The URL may still be relative to the Markdown file. In that case the
	// synthetic GitHub URL above already resolved it for us.
	const expectedBase = `/blob/${encodeRef(context.ref)}/`;

	if (pathname.startsWith(expectedBase)) {
		const path = decodePath(pathname.slice(expectedBase.length));
		return path || null;
	}

	// The URL was relative to the README and therefore starts from the
	// repository path generated by the synthetic base.
	const blobPrefix = `${repoPrefix}blob/${encodeRef(context.ref)}/`;

	if (pathname.startsWith(blobPrefix)) {
		const path = decodePath(pathname.slice(blobPrefix.length));
		return path || null;
	}

	// Keep these variables explicit so accidental cross-repository URLs don't
	// become repository assets later.
	void owner;
	void repo;

	return null;
}

export function buildRepoAssetPath(
	path: string,
	ref: string,
	shareId: string,
): string {
	const params = new URLSearchParams({
		path,
		ref,
		s: shareId,
	});

	return `/api/asset?${params.toString()}`;
}

export function repairRepoImages(
	html: string,
	context: RepoAssetContext,
	shareId: string,
): string {
	return html.replace(
		/(<img\b[^>]*\bsrc\s*=\s*)(["'])([^"']+)\2/gi,
		(match, prefix: string, quote: string, rawSrc: string) => {
			const path = resolveRepoImagePath(rawSrc, context);

			if (!path) {
				return match;
			}

			const src = buildRepoAssetPath(path, context.ref, shareId);

			return `${prefix}${quote}${src}${quote}`;
		},
	);
}
